var secondsPerMin = 60;
var minsPerHour = 60;
var hoursPerDay = 24;
var daysPerWeek = 7;
var weeksPerYear = 52;
var secondsPerDay = secondsPerMin * minsPerHour * hoursPerDay;
document.write('There are ' + secondsPerDay + ' seconds in a day.');
var yearsAlive = 29;
var daysPerYear = 365;
var secondsAlive = secondsPerDay * daysPerYear * yearsAlive;
document.write(' I have been alive for ' + yearsAlive + ' years or ' + secondsAlive + ' seconds.');
